language:       cpp

matrix:
  include:
    # / Linux Clang
    - os: linux
      compiler: clang
      addons:
        apt:
          packages: 
            - freeglut3-dev 
            - libxi-dev
            - libxmu-dev

    - os: osx
      osx-image: xcode9.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - freeglut

before_install:
  - rm -rf deps
  - mkdir deps
  - git clone https://github.com/libglui/glui deps/glui
  - cd deps/glui
  - make
  - sudo cp lib/libglui.a /usr/local/lib
  - sudo cp include/GL/glui.h /usr/local/include
  - cd ..
  - pip install --user cpp-coveralls

script:
  - make
